#!/usr/local/bin/tclsh

source eecwords.tcl
source eecparse.tcl
source eecmachine.tcl

puts stderr eec:[llength $argv],$argv.

foreach arg [linsert argv 0 starting.eec] {
    
    puts stderr eec,argv:$arg.

    switch -glob -- $arg {

	-*      { 
	    puts stderr "eec has no arguments yet."
	    puts stderr " check your command line: $argv"
	    exit 
	}
	default { eec_include $arg }
    }
}
