#!/usr/bin/env python

import os
import sys

import datastructure
import machine
import parser

# print dir(machine)
# print dir(parser)
# print 'datastructure: ', dir(datastructure)

# print "="*52
# print parser.cummings
# print parser.handler


def bigLine( msg, n):

    l = len(msg)
    f = (n - (l+2))/2
    b = "="*f
    print b, msg, b

def framer( name, parent, *args):

    c = machine.Frame(name, parent)

    for a in args:
        # print a
        c.insertArg(a)
        
    bigLine('Frame of C', 80)
    print str(c)

    bigLine('Evaluate C', 80)

    c.evaluate()



thisFrame = machine.Frame('interpreter', None)

framer( 'comment', thisFrame, 'this is a comment', 'this is another')
